### ISSUE TITLE
How To Get The Value Once Colors Are Choosen

### ISSUE THREAD

**Issue by varunsridharan** [Simonwep/gpickr#1]
Hi,

I can't find any documentation on how to get the value once user has finished updating the GPickr
Can you please update it here or in docs on how to do it ?

**Comment by simonwep** [comment]
There was until now currently no way, the library isn't even near a ready-to use state. Anyway, i've added `getGradient`, `getStops` and `getAngle` which can be used to obtain / process the current state :)

**Comment by varunsridharan** [comment]
@Simonwep sorry i was not aware of it !! i hope this gets done soon :-) and will be able to use it in my project. also let me know in which way i could help you on this .

also i just noticed that gradient picker is not working properly in mobile devices. i mean i am not able to switch between circle and line.
